name = "Y2K4's Modpack"
author = "Y2K4"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd8fddf566e6b662ed4f2b4f8bd19d79156c81dbc2ece1bb07d4cc29b0e66522"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
